In [2]:
import folium
import pandas as pd
from folium.plugins import MarkerCluster
from folium.plugins import MousePosition
from folium.features import DivIcon

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'

spacex_df=pd.read_csv(URL)
spacex_df

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.00,LEO,SpaceX,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.00,LEO (ISS),NASA (COTS) NRO,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.00,LEO (ISS),NASA (COTS),No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.00,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.00,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
5,7,2013-12-03,22:41:00,F9 v1.1,CCAFS LC-40,SES-8,3170.00,GTO,SES,No attempt,0,28.562302,-80.577356
6,8,2014-01-06,22:06:00,F9 v1.1,CCAFS LC-40,Thaicom 6,3325.00,GTO,Thaicom,No attempt,0,28.562302,-80.577356
7,9,2014-04-18,19:25:00,F9 v1.1,CCAFS LC-40,SpaceX CRS-3,2296.00,LEO (ISS),NASA (CRS),Controlled (ocean),0,28.562302,-80.577356
8,10,2014-07-14,15:15:00,F9 v1.1,CCAFS LC-40,OG2 Mission 1 6 Orbcomm-OG2 satellites,1316.00,LEO,Orbcomm,Controlled (ocean),0,28.562302,-80.577356
9,11,2014-08-05,8:00:00,F9 v1.1,CCAFS LC-40,AsiaSat 8,4535.00,GTO,AsiaSat,No attempt,0,28.562302,-80.577356
10,12,2014-09-07,5:00:00,F9 v1.1 B1011,CCAFS LC-40,AsiaSat 6,4428.00,GTO,AsiaSat,No attempt,0,28.562302,-80.577356
11,13,2014-09-21,5:52:00,F9 v1.1 B1010,CCAFS LC-40,SpaceX CRS-4,2216.00,LEO (ISS),NASA (CRS),Uncontrolled (ocean),0,28.562302,-80.577356
12,14,2015-01-10,9:47:00,F9 v1.1 B1012,CCAFS LC-40,SpaceX CRS-5,2395.00,LEO (ISS),NASA (CRS),Failure (drone ship),0,28.562302,-80.577356
13,15,2015-02-11,23:03:00,F9 v1.1 B1013,CCAFS LC-40,DSCOVR,570.00,Sun–Earth L1,U.S. Air Force NASA NOAA,Controlled (ocean),0,28.562302,-80.577356
14,16,2015-03-02,3:50:00,F9 v1.1 B1014,CCAFS LC-40,ABS-3A Eutelsat 115 West B,4159.00,GTO,ABS Eutelsat,No attempt,0,28.562302,-80.577356
15,17,2015-04-14,20:10:00,F9 v1.1 B1015,CCAFS LC-40,SpaceX CRS-6,1898.00,LEO (ISS),NASA (CRS),Failure (drone ship),0,28.562302,-80.577356
16,18,2015-04-27,23:03:00,F9 v1.1 B1016,CCAFS LC-40,TürkmenÄlem 52°E / MonacoSAT,4707.00,GTO,Turkmenistan National Space Agency,No attempt,0,28.562302,-80.577356
17,19,2015-06-28,14:21:00,F9 v1.1 B1018,CCAFS LC-40,SpaceX CRS-7,1952.00,LEO (ISS),NASA (CRS),Precluded (drone ship),1,28.562302,-80.577356
18,20,2015-12-22,1:29:00,F9 FT B1019,CCAFS LC-40,OG2 Mission 2 11 Orbcomm-OG2 satellites,2034.00,LEO,Orbcomm,Success (ground pad),1,28.562302,-80.577356
19,22,2016-03-04,23:35:00,F9 FT B1020,CCAFS LC-40,SES-9,5271.00,GTO,SES,Failure (drone ship),0,28.562302,-80.577356
20,23,2016-04-08,20:43:00,F9 FT B1021.1,CCAFS LC-40,SpaceX CRS-8,3136.00,LEO (ISS),NASA (CRS),Success (drone ship),1,28.562302,-80.577356
21,24,2016-05-06,5:21:00,F9 FT B1022,CCAFS LC-40,JCSAT-14,4696.00,GTO,SKY Perfect JSAT Group,Success (drone ship),1,28.562302,-80.577356
22,25,2016-05-27,21:39:00,F9 FT B1023.1,CCAFS LC-40,Thaicom 8,3100.00,GTO,Thaicom,Success (drone ship),1,28.562302,-80.577356
23,26,2016-06-15,14:29:00,F9 FT B1024,CCAFS LC-40,ABS-2A Eutelsat 117 West B,3600.00,GTO,ABS Eutelsat,Failure (drone ship),0,28.562302,-80.577356
24,27,2016-07-18,4:45:00,F9 FT B1025.1,CCAFS LC-40,SpaceX CRS-9,2257.00,LEO (ISS),NASA (CRS),Success (ground pad),1,28.562302,-80.577356
25,28,2016-08-14,5:26:00,F9 FT B1026,CCAFS LC-40,JCSAT-16,4600.00,GTO,SKY Perfect JSAT Group,Success (drone ship),1,28.562302,-80.577356
26,6,2013-09-29,16:00:00,F9 v1.1 B1003,VAFB SLC-4E,CASSIOPE,500.00,Polar LEO,MDA,Uncontrolled (ocean),0,34.632834,-120.610745
27,21,2016-01-17,18:42:00,F9 v1.1 B1017,VAFB SLC-4E,Jason-3,553.00,LEO,NASA (LSP) NOAA CNES,Failure (drone ship),0,34.632834,-120.610745
28,29,2017-01-14,17:54:00,F9 FT B1029.1,VAFB SLC-4E,Iridium NEXT 1,9600.00,Polar LEO,Iridium Communications,Success (drone ship),1,34.632834,-120.610745
29,37,2017-06-25,20:25:00,F9 FT B1036.1,VAFB SLC-4E,Iridium NEXT 2,9600.00,LEO,Iridium Communications,Success (drone ship),1,34.632834,-120.610745
30,40,2017-08-24,18:51:00,F9 FT B1038.1,VAFB SLC-4E,Formosat-5,475.00,SSO,NSPO,Success (drone ship),1,34.632834,-120.610745
31,42,2017-10-09,12:37:00,F9 B4 B1041.1,VAFB SLC-4E,Iridium NEXT 3,9600.00,Polar LEO,Iridium Communications,Success (drone ship),1,34.632834,-120.610745
32,46,2017-12-23,1:27:00,F9 FT B1036.2,VAFB SLC-4E,Iridium NEXT 4,9600.00,Polar LEO,Iridium Communications,Controlled (ocean),0,34.632834,-120.610745
33,49,2018-02-22,14:17:00,F9 FT B1038.2,VAFB SLC-4E,Paz Tintin A & B,2150.00,SSO,Hisdesat exactEarth SpaceX,No attempt,0,34.632834,-120.610745
34,51,2018-03-30,14:14:00,F9 B4 B1041.2,VAFB SLC-4E,Iridium NEXT 5,9600.00,Polar LEO,Iridium Communications,No attempt,0,34.632834,-120.610745
35,55,2018-05-22,19:47:58,F9 B4 B1043.2,VAFB SLC-4E,"Iridium NEXT 6 GRACE-FO 1, 2",6460.00,Polar LEO,Iridium Communications GFZ • NASA,No attempt,0,34.632834,-120.610745
36,30,2017-02-19,14:39:00,F9 FT B1031.1,KSC LC-39A,SpaceX CRS-10,2490.00,LEO (ISS),NASA (CRS),Success (ground pad),1,28.573255,-80.646895
37,31,2017-03-16,6:00:00,F9 FT B1030,KSC LC-39A,EchoStar 23,5600.00,GTO,EchoStar,No attempt,0,28.573255,-80.646895
38,32,2017-03-30,22:27:00,F9 FT B1021.2,KSC LC-39A,SES-10,5300.00,GTO,SES,Success (drone ship),1,28.573255,-80.646895
39,33,2017-05-01,11:15:00,F9 FT B1032.1,KSC LC-39A,NROL-76,3696.65,LEO,NRO,Success (ground pad),1,28.573255,-80.646895
40,34,2017-05-15,23:21:00,F9 FT B1034,KSC LC-39A,Inmarsat-5 F4,6070.00,GTO,Inmarsat,No attempt,0,28.573255,-80.646895
41,35,2017-06-03,21:07:00,F9 FT B1035.1,KSC LC-39A,SpaceX CRS-11,2708.00,LEO (ISS),NASA (CRS),Success (ground pad),1,28.573255,-80.646895
42,36,2017-06-23,19:10:00,F9 FT B1029.2,KSC LC-39A,BulgariaSat-1,3669.00,GTO,Bulsatcom,Success (drone ship),1,28.573255,-80.646895
43,38,2017-07-05,23:38:00,F9 FT B1037,KSC LC-39A,Intelsat 35e,6761.00,GTO,Intelsat,No attempt,0,28.573255,-80.646895
44,39,2017-08-14,16:31:00,F9 B4 B1039.1,KSC LC-39A,SpaceX CRS-12,3310.00,LEO (ISS),NASA (CRS),Success (ground pad),1,28.573255,-80.646895
45,41,2017-09-07,14:00:00,F9 B4 B1040.1,KSC LC-39A,Boeing X-37B OTV-5,4990.00,LEO,U.S. Air Force,Success (ground pad),1,28.573255,-80.646895
46,43,2017-10-11,22:53:00,F9 FT B1031.2,KSC LC-39A,SES-11 / EchoStar 105,5200.00,GTO,SES EchoStar,Success (drone ship),1,28.573255,-80.646895
47,44,2017-10-30,19:34:00,F9 B4 B1042.1,KSC LC-39A,Koreasat 5A,3500.00,GTO,KT Corporation,Success (drone ship),1,28.573255,-80.646895
48,54,2018-05-11,20:14:00,F9 B5 B1046.1,KSC LC-39A,Bangabandhu-1,3600.00,GTO,Thales-Alenia/BTRC,Success (drone ship),1,28.573255,-80.646895
49,45,2017-12-15,15:36:00,F9 FT B1035.2,CCAFS SLC-40,SpaceX CRS-13,2205.00,LEO (ISS),NASA (CRS),Success (ground pad),1,28.563197,-80.576820
50,47,2018-01-08,1:00:00,F9 B4 B1043.1,CCAFS SLC-40,Zuma,3696.65,LEO,Northrop Grumman,Success (ground pad),1,28.563197,-80.576820
51,48,2018-01-31,21:25:00,F9 FT B1032.2,CCAFS SLC-40,GovSat-1 / SES-16,4230.00,GTO,SES,Controlled (ocean),0,28.563197,-80.576820
52,50,2018-03-06,5:33:00,F9 B4 B1044,CCAFS SLC-40,Hispasat 30W-6 PODSat,6092.00,GTO,Hispasat NovaWurks,No attempt,0,28.563197,-80.576820
53,52,2018-04-02,20:30:00,F9 B4 B1039.2,CCAFS SLC-40,SpaceX CRS-14,2647.00,LEO (ISS),NASA (CRS),No attempt,0,28.563197,-80.576820
54,53,2018-04-18,22:51:00,F9 B4 B1045.1,CCAFS SLC-40,Transiting Exoplanet Survey Satellite (TESS),362.00,HEO,NASA (LSP),Success (drone ship),1,28.563197,-80.576820
55,56,2018-06-04,4:45:00,F9 B4 B1040.2,CCAFS SLC-40,SES-12,5384.00,GTO,SES,No attempt,0,28.563197,-80.576820

## Task 1: Mark all launch sites on a map

In [3]:
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

We first need to create a folium Map object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [4]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

In [5]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 20; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

Now, let's add a circle for each launch site in data frame launch_sites

TODO: Create and add folium.Circle and folium.Marker for each launch site on the site map

An example of folium.Circle:

folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))

An example of folium.Marker:

folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))

In [6]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label

for lat, lng, lab in zip(launch_sites_df.Lat,launch_sites_df.Long, launch_sites_df['Launch Site']):
    site_map.add_child(folium.Circle(
        [lat,lng], 
        radius=50, 
        color='#d35400', 
        fill=True
        ).add_child(folium.Popup(lab)))
    marker = folium.map.Marker(
        [lat,lng],
        # Create an icon as a text label
        icon=DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html='<div style="font-size: 20; color:#d35400;"><b>%s</b></div>' % lab,))
    site_map.add_child(marker)


site_map

## Task 2: Mark the success/failed launches for each site on the map

In [7]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records. If a launch was successful (class=1), then we use a green marker and if a launch was failed, we use a red marker (class=0)

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

In [8]:
marker_cluster = MarkerCluster()

In [9]:
spacex_df['marker_color']=spacex_df['class'].map({1:'green',0:'red'})
spacex_df

     Launch Site        Lat        Long  class marker_color
0    CCAFS LC-40  28.562302  -80.577356      0          red
1    CCAFS LC-40  28.562302  -80.577356      0          red
2    CCAFS LC-40  28.562302  -80.577356      0          red
3    CCAFS LC-40  28.562302  -80.577356      0          red
4    CCAFS LC-40  28.562302  -80.577356      0          red
5    CCAFS LC-40  28.562302  -80.577356      0          red
6    CCAFS LC-40  28.562302  -80.577356      0          red
7    CCAFS LC-40  28.562302  -80.577356      0          red
8    CCAFS LC-40  28.562302  -80.577356      0          red
9    CCAFS LC-40  28.562302  -80.577356      0          red
10   CCAFS LC-40  28.562302  -80.577356      0          red
11   CCAFS LC-40  28.562302  -80.577356      0          red
12   CCAFS LC-40  28.562302  -80.577356      0          red
13   CCAFS LC-40  28.562302  -80.577356      0          red
14   CCAFS LC-40  28.562302  -80.577356      0          red
15   CCAFS LC-40  28.562302  -80.577356      0          red
16   CCAFS LC-40  28.562302  -80.577356      0          red
17   CCAFS LC-40  28.562302  -80.577356      1        green
18   CCAFS LC-40  28.562302  -80.577356      1        green
19   CCAFS LC-40  28.562302  -80.577356      0          red
20   CCAFS LC-40  28.562302  -80.577356      1        green
21   CCAFS LC-40  28.562302  -80.577356      1        green
22   CCAFS LC-40  28.562302  -80.577356      1        green
23   CCAFS LC-40  28.562302  -80.577356      0          red
24   CCAFS LC-40  28.562302  -80.577356      1        green
25   CCAFS LC-40  28.562302  -80.577356      1        green
26   VAFB SLC-4E  34.632834 -120.610745      0          red
27   VAFB SLC-4E  34.632834 -120.610745      0          red
28   VAFB SLC-4E  34.632834 -120.610745      1        green
29   VAFB SLC-4E  34.632834 -120.610745      1        green
30   VAFB SLC-4E  34.632834 -120.610745      1        green
31   VAFB SLC-4E  34.632834 -120.610745      1        green
32   VAFB SLC-4E  34.632834 -120.610745      0          red
33   VAFB SLC-4E  34.632834 -120.610745      0          red
34   VAFB SLC-4E  34.632834 -120.610745      0          red
35   VAFB SLC-4E  34.632834 -120.610745      0          red
36    KSC LC-39A  28.573255  -80.646895      1        green
37    KSC LC-39A  28.573255  -80.646895      0          red
38    KSC LC-39A  28.573255  -80.646895      1        green
39    KSC LC-39A  28.573255  -80.646895      1        green
40    KSC LC-39A  28.573255  -80.646895      0          red
41    KSC LC-39A  28.573255  -80.646895      1        green
42    KSC LC-39A  28.573255  -80.646895      1        green
43    KSC LC-39A  28.573255  -80.646895      0          red
44    KSC LC-39A  28.573255  -80.646895      1        green
45    KSC LC-39A  28.573255  -80.646895      1        green
46    KSC LC-39A  28.573255  -80.646895      1        green
47    KSC LC-39A  28.573255  -80.646895      1        green
48    KSC LC-39A  28.573255  -80.646895      1        green
49  CCAFS SLC-40  28.563197  -80.576820      1        green
50  CCAFS SLC-40  28.563197  -80.576820      1        green
51  CCAFS SLC-40  28.563197  -80.576820      0          red
52  CCAFS SLC-40  28.563197  -80.576820      0          red
53  CCAFS SLC-40  28.563197  -80.576820      0          red
54  CCAFS SLC-40  28.563197  -80.576820      1        green
55  CCAFS SLC-40  28.563197  -80.576820      0          red

In [10]:
site_map.add_child(marker_cluster)

for index, record in spacex_df.iterrows():
    marker=folium.Marker(location=[record['Lat'], record['Long']], icon=folium.Icon(color='white',icon_color=record['marker_color']))
    marker_cluster.add_child(marker)

site_map

## TASK 3: Calculate the distances between a launch site to its proximities

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [11]:
# # Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
# formatter = "function(num) {return L.Util.formatNum(num, 5);};"
# mouse_position = MousePosition(
#     position='topright',
#     separator=' Long: ',
#     empty_string='NaN',
#     lng_first=False,
#     num_digits=20,
#     prefix='Lat:',
#     lat_formatter=formatter,
#     lng_formatter=formatter,
# )

# site_map.add_child(mouse_position)
# site_map

## TASK 3: Calculate the distances between a launch site to its proximities

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [12]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [13]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [14]:
# find coordinate of the closet coastline e.g.,: Lat: 28.56367  Lon: -80.57163
# distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

launch_site_lat=28.5634
launch_site_lon=-80.57676
Lat= 28.56291
Lon= -80.56769
distance=calculate_distance(launch_site_lat, launch_site_lon, Lat,Lon)
distance

0.8877421895427641

In [15]:
distance_marker = folium.Marker(
   [Lat,Lon],
   icon=DivIcon(
       icon_size=(20,20),
       icon_anchor=(0,0),
       html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
       )
   )
site_map.add_child(distance_marker)

In [16]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
coordinates=[[launch_site_lat, launch_site_lon],[Lat,Lon]]
lines=folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(lines)

In [17]:
Lat= 28.561969141993803
Lon= -80.570664656468967
distance=calculate_distance(launch_site_lat, launch_site_lon, Lat,Lon)
distance_marker = folium.Marker(
   [Lat,Lon],
   icon=DivIcon(
       icon_size=(20,20),
       icon_anchor=(0,0),
       html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
       )
   )
site_map.add_child(distance_marker)
coordinates=[[launch_site_lat, launch_site_lon],[Lat,Lon]]
lines=folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(lines)

In [18]:
launch_site_lat=28.57324963567089
launch_site_lon=-80.64690200552842
Lat= 28.57261814543234
Lon= -80.65391804050375
distance=calculate_distance(launch_site_lat, launch_site_lon, Lat,Lon)
distance_marker = folium.Marker(
   [Lat,Lon],
   icon=DivIcon(
       icon_size=(20,20),
       icon_anchor=(0,0),
       html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
       )
   )
site_map.add_child(distance_marker)
coordinates=[[launch_site_lat, launch_site_lon],[Lat,Lon]]
lines=folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(lines)

In [19]:
launch_site_lat=34.63284210497675
launch_site_lon=-120.61075896652021
Lat= 34.63858769998481
Lon= -120.45790885890023
distance=calculate_distance(launch_site_lat, launch_site_lon, Lat,Lon)
distance_marker = folium.Marker(
   [Lat,Lon],
   icon=DivIcon(
       icon_size=(20,20),
       icon_anchor=(0,0),
       html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
       )
   )
site_map.add_child(distance_marker)
coordinates=[[launch_site_lat, launch_site_lon],[Lat,Lon]]
lines=folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(lines)